### ISSUE TITLE
Is.Nil

### ISSUE THREAD

**Issue by corbym** [amahdavian/async-event-bus#1]
This project looks great 👍

I just wanted to say it's nice to see my humble gocrest module being used in earnest.

I did notice that you could use `is.Nil` rather than using `== nil, is.True()`.. it's a bit more descriptive when it fails.

Nice stuff  🙂

https://github.com/amahdavian/async-event-bus/blob/ed96ed1b75b138a50e60d20bfc9f9355a17d4863/internal/concurrency/map_test.go#L100

**Comment by amin-tyro** [comment]
Hi @corbym,
Your module is awesome, we use it extensively in all our apps.
Going back to your question, the reason I did not use `is.Nil()` is because `actual` is a slice and its zero-value is not comparable to a pointer's zero-value. Hence, using `is.Nil` will cause the test to fail with below error:
```
=== RUN   TestShouldRemoveValueAndDeleteKeyWhenOnlyOneValueIsAssociatedWithGivenKey
    map_test.go:100: 
        Expected: value equal to <<nil>>
             but: <[]>
--- FAIL: TestShouldRemoveValueAndDeleteKeyWhenOnlyOneValueIsAssociatedWithGivenKey (829.28s)
```
There are few workarounds for this:
1. Create a custom matcher which can handle these scenarios, `<Type>Nil()`
2. Create a nil var of the type and use `is.Equals`
3. Do the `nil` check and assert that it's `true`

**Comment by amahdavian** [comment]
Hi @corbym,
Your module is awesome, we use it extensively in all our apps.
Going back to your question, the reason I did not use `is.Nil()` is because `actual` is a slice and its zero-value is not comparable to a pointer's zero-value. Hence, using `is.Nil` will cause the test to fail with below error:
```
=== RUN   TestShouldRemoveValueAndDeleteKeyWhenOnlyOneValueIsAssociatedWithGivenKey
    map_test.go:100: 
        Expected: value equal to <<nil>>
             but: <[]>
--- FAIL: TestShouldRemoveValueAndDeleteKeyWhenOnlyOneValueIsAssociatedWithGivenKey (829.28s)
```
There are few workarounds for this:
1. Create a custom matcher which can handle these scenarios, `<Type>Nil()`
2. Create a nil var of the type and use `is.Equals`
3. Do the `nil` check and assert that it's `true`

**Comment by corbym** [comment]
sounds like I need to do some fixin' in gocrest :) I will look into it.

**Comment by corbym** [comment]
This should be fixed in the next version of the matchers and is available
in the master branch now.

**Comment by amahdavian** [comment]
Very nice, thanks for that. I just updated a bunch of our apps (private repos) and it's working flawlessly :+1:
